include common.mk

tstls = $(shell cd $(base)/src/video-js/test; ls *.html)


run-report: $(tstls)
	echo $(tstls)

%.html:
	mkdir -p video-js.results
	echo "$@---------------------------" >> $(base)/log/saga.log
	$(sagacmd) -b $(base)/src/video-js/ -i test/$@ \
               -o video-js.results -s PER_TEST -n '.*test.*js$$' 2>&1 \
               >> $(base)/log/saga.log
	$(base)/bin/analyze/saga.rb video-js.results/test/$@-report.html |\
               tee -a $(base)/log/video-js-report.log
