include common.mk

tstls = $(shell cd $(base)/src/knockout/spec; ls *.html)


run-report: $(tstls)
	echo $(tstls)

%.html:
	mkdir -p knockout.results
	echo "$@---------------------------" >> $(base)/log/saga.log
	$(sagacmd) -b $(base)/src/knockout/ -i spec/$@ \
               -o knockout.results -s PER_TEST -n '.*test.*js$$' 2>&1 \
               >> $(base)/log/saga.log
	$(base)/bin/analyze/saga.rb knockout.results/spec/$@-report.html |\
               tee -a $(base)/log/knockout-report.log
