include common.mk

tstls = $(shell cd $(base)/src/jsrender/test; ls *.html)


run-report: $(tstls)
	echo $(tstls)

%.html:
	mkdir -p jsrender.results
	echo "$@---------------------------" >> $(base)/log/saga.log
	$(sagacmd) -b $(base)/src/jsrender/ -i test/$@ \
               -o jsrender.results -s PER_TEST -n '.*test.*js$$' 2>&1 \
               >> $(base)/log/saga.log
	$(base)/bin/analyze/saga.rb jsrender.results/test/$@-report.html |\
               tee -a $(base)/log/jsrender-report.log
