include common.mk

tstls = $(shell cd $(base)/src/list/tests; ls *.html)


run-report: $(tstls)
	echo $(tstls)

%.html:
	mkdir -p list.results
	echo "$@---------------------------" >> $(base)/log/saga.log
	$(sagacmd) -b $(base)/src/list/ -i tests/$@ \
               -o list.results -s PER_TEST -n '.*test.*js$$' 2>&1 \
               >> $(base)/log/saga.log
	$(base)/bin/analyze/saga.rb list.results/tests/$@-report.html |\
               tee -a $(base)/log/list-report.log
