include common.mk

tstls = $(shell cd $(base)/src/jquery-validation/test; ls index.html)


run-report: $(tstls)
	echo $(tstls)

%.html:
	mkdir -p jquery-validation.results
	echo "$@---------------------------" >> $(base)/log/saga.log
	$(sagacmd) -b $(base)/src/jquery-validation/ -i test/$@ \
               -o jquery-validation.results -s PER_TEST -n '.*test.*js$$' 2>&1 \
               |tee -a $(base)/log/saga.log
	$(base)/bin/analyze/saga.rb jquery-validation.results/test/$@-report.html |\
               tee -a $(base)/log/jquery-validation-report.log
