include common.mk

tstls = $(shell cd $(base)/src/jwysiwyg/test; ls *.html)


run-report: $(tstls)
	echo $(tstls)

%.html:
	mkdir -p jwysiwyg.results
	echo "$@---------------------------" >> $(base)/log/saga.log
	$(sagacmd) -b $(base)/src/jwysiwyg/ -i test/$@ \
               -o jwysiwyg.results -s PER_TEST -n '.*test.*js$$' 2>&1 \
               >> $(base)/log/saga.log
	$(base)/bin/analyze/saga.rb jwysiwyg.results/test/$@-report.html |\
               tee -a $(base)/log/jwysiwyg-report.log
