include common.mk

tstls = $(shell cd $(base)/src/jquery/test; ls *-test.html)


run-report: $(tstls)
	echo $(tstls)

%-test.html:
	mkdir -p jquery.results
	echo "$@---------------------------" >> $(base)/log/saga.log
	$(sagacmd) -b $(base)/src/jquery/ -i test/$@ \
               -o jquery.results -s PER_TEST -n '.*test.*js$$' 2>&1 \
               >> $(base)/log/saga.log
	$(base)/bin/analyze/saga.rb jquery.results/test/$@-report.html |\
               tee -a $(base)/log/jquery-report.log
