include common.mk

tstls = $(shell cd $(base)/src/qc.js/test; ls *.html)


run-report: $(tstls)
	echo $(tstls)

%.html:
	mkdir -p qc.js.results
	echo "$@---------------------------" >> $(base)/log/saga.log
	$(sagacmd) -b $(base)/src/qc.js/ -i test/$@ \
               -o qc.js.results -s PER_TEST -n '.*test.*js$$' 2>&1 \
               >> $(base)/log/saga.log
	$(base)/bin/analyze/saga.rb qc.js.results/test/$@-report.html |\
               tee -a $(base)/log/qc.js-report.log
