include common.mk

tstls = $(shell cd $(base)/src/ember.js/tests; ls *.html)


run-report: $(tstls)
	echo $(tstls)

%.html:
	mkdir -p ember.js.results
	echo "$@---------------------------" >> $(base)/log/saga.log
	$(sagacmd) -b $(base)/src/ember.js/ -i tests/$@ \
               -o ember.js.results -s PER_TEST -n '.*test.*js$$' 2>&1 \
               >> $(base)/log/saga.log
	$(base)/bin/analyze/saga.rb ember.js.results/tests/$@-report.html |\
               tee -a $(base)/log/ember.js-report.log
